baseURL: /
title: "themihel.me | Mischa Helfenstein"
theme: "thml"
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
staticDir:
  - static
disableKinds:
  - taxonomy
  - taxonomyTerm
  - sitemap
  - RSS
  - page
